### ISSUE TITLE
Differentiate error messages for a missing URL and an invalid one

### ISSUE THREAD

**Issue by whatyouhide** [dehlic/ze.lc#2]
If I submit an empty form, the error message is that the URL isn't a valid one. Wouldn't it be better if the error message was that the URL is missing?

I don't know if it would be easier, at this point, to validate both the URL presence and its validity in the fronted instead of issuing a request to the server.

**Comment by coire1** [comment]
I agree, I think it's better to add validations at client level.

**Comment by whatyouhide** [comment]
This was fixed by 942180c as far as I understand :+1:
