### ISSUE TITLE
"Copy to clipboard" button retains hover style after the cursor leaves

### ISSUE THREAD

**Issue by whatyouhide** [dehlic/ze.lc#4]
Before:
![screen shot 2014-10-29 at 12 19 36](https://cloud.githubusercontent.com/assets/3890250/4824717/988d8502-5f5d-11e4-9a59-c59fd627962e.png)

After (even without the hovering pointer):
![screen shot 2014-10-29 at 12 19 44](https://cloud.githubusercontent.com/assets/3890250/4824722/abf42dee-5f5d-11e4-963d-4a5da675186c.png)

**Comment by coire1** [comment]
Which browser?

**Comment by whatyouhide** [comment]
![screen shot 2014-10-29 at 12 24 12](https://cloud.githubusercontent.com/assets/3890250/4824771/1db49860-5f5e-11e4-858a-796d38dc8aea.png)

**Comment by whatyouhide** [comment]
Closing this!
